package repo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"iag-procurement/backend/internal/events"
	"iag-procurement/backend/internal/models"
)

// GetInvoice returns a single invoice with its link + settlement fields.
// Returns ErrNotFound when the id does not exist.
func (p *Procurement) GetInvoice(ctx context.Context, id string) (*models.Invoice, error) {
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, fmt.Errorf("%w: id is required", ErrInvalidArgument)
	}
	var inv models.Invoice
	var invNo, poID, grnID *string
	var idate, pdate *time.Time
	err := p.pool.QueryRow(ctx, `
		SELECT id, invoice_no, vendor_id, po_id, grn_id, amount, currency, status, match_status, invoice_date, payment_date, payment_method
		FROM invoices WHERE id = $1`, id,
	).Scan(&inv.ID, &invNo, &inv.VendorID, &poID, &grnID, &inv.Amount, &inv.Currency, &inv.Status, &inv.MatchStatus, &idate, &pdate, &inv.PaymentMethod)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	inv.InvoiceNo = invNo
	inv.PoID = poID
	inv.GrnID = grnID
	if idate != nil {
		inv.InvoiceDate = idate.UTC().Format("2006-01-02")
	}
	if pdate != nil {
		inv.PaymentDate = pdate.UTC().Format("2006-01-02")
	}
	return &inv, nil
}

// CreateVendor inserts a vendor master row and audit trail entry.
func (p *Procurement) CreateVendor(ctx context.Context, name, logo, category, contact, email, phone, country, terms string, rating float64, status string, auditUser string) (*models.Vendor, error) {
	if strings.TrimSpace(name) == "" {
		return nil, fmt.Errorf("%w: name is required", ErrInvalidArgument)
	}
	if status == "" {
		status = "Active"
	}
	id := newProcurementID("V")
	// Mint the shared party_id up front so the same canonical key is persisted
	// locally and carried on the party.vendor.upserted event to the mesh.
	partyID := uuid.NewString()
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `
		INSERT INTO vendors (id, name, logo, category, contact, email, phone, country, terms, rating, status, total_spend, open_pos, party_id)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::uuid)`,
		id, name, logo, category, contact, email, phone, country, terms, rating, status, 0, 0, partyID,
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("vendor %s", name),
	); err != nil {
		return nil, err
	}
	if err := p.enqueueVendorUpsertedTx(ctx, tx, events.VendorUpsert{
		PartyID: partyID, Code: id, Name: name, Category: category,
		Email: email, Phone: phone, Country: country, Status: status,
	}); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return &models.Vendor{
		ID: id, Name: name, Logo: logo, Category: category, Contact: contact, Email: email,
		Phone: phone, Country: country, Terms: terms, Rating: rating, Status: status,
		TotalSpend: 0, OpenPOs: 0,
	}, nil
}

// CreateItem inserts a catalog item row and audit trail entry.
func (p *Procurement) CreateItem(ctx context.Context, sku, name, category, uom string, stock, reorder, lastPrice float64, currency, preferredVendorID string, attrs json.RawMessage, auditUser string) (*models.Item, error) {
	sku = strings.TrimSpace(sku)
	name = strings.TrimSpace(name)
	if sku == "" || name == "" {
		return nil, fmt.Errorf("%w: sku and name are required", ErrInvalidArgument)
	}
	if currency == "" {
		currency = "USD"
	}
	// The id is left to the column's own DEFAULT gen_random_uuid().
	//
	// Migration 027 retyped items.id from TEXT to UUID on the stated premise
	// that "every id in this service is already generated by uuid.NewString()".
	// That is not true of newProcurementID, which produces PREFIX-<8 hex>, so
	// inserting an explicit id here fails with "invalid input syntax for type
	// uuid" on every database that has run 027 — this create path has been dead
	// since. Nothing reads the ITM- prefix.
	//
	// The same mismatch is present in every other Create* in this package
	// (vendors, budgets, RFQs, GRNs, invoices, requisitions, POs, payments,
	// quotes, contracts). Those are not fixed here: some of their prefixes look
	// like human-facing references (PR-2026-…, PO-2026-…) and deciding where
	// that number lives now is a design question, not a mechanical edit.
	pv := strings.TrimSpace(preferredVendorID)
	var pref interface{}
	if pv != "" {
		pref = pv
	}

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	var id string
	if err := tx.QueryRow(ctx, `
		INSERT INTO items (sku, name, category, uom, stock, reorder, last_price, currency, preferred_vendor_id, attrs)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,COALESCE($10::jsonb, '{}'::jsonb))
		RETURNING id`,
		sku, name, category, uom, stock, reorder, lastPrice, currency, pref, nullableJSON(attrs),
	).Scan(&id); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("sku=%s", sku),
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	out := models.Item{
		ID: id, SKU: sku, Name: name, Category: category, UOM: uom,
		Stock: stock, Reorder: reorder, LastPrice: lastPrice, Currency: currency,
		Attrs: attrs,
	}
	if pv != "" {
		out.PreferredVendor = pv
	}
	return &out, nil
}

// nullableJSON turns "the caller sent nothing" into a real SQL NULL, which the
// COALESCE above then reads as the empty bag. An empty json.RawMessage reaches
// a jsonb column as an empty string, which is not valid JSON and fails.
func nullableJSON(raw json.RawMessage) any {
	if len(raw) == 0 {
		return nil
	}
	return []byte(raw)
}

// CreateBudget inserts a budget envelope and audit trail entry.
func (p *Procurement) CreateBudget(ctx context.Context, code, period string, allocated float64, dept string, auditUser string) (*models.Budget, error) {
	code = strings.TrimSpace(code)
	if code == "" {
		return nil, fmt.Errorf("%w: code is required", ErrInvalidArgument)
	}
	id := newProcurementID("BDG")
	committed, spent := 0.0, 0.0
	remaining := allocated - committed - spent

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `
		INSERT INTO budgets (id, code, period, allocated, committed, spent, remaining, dept)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
		id, code, period, allocated, committed, spent, remaining, dept,
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("code=%s allocated=%.2f", code, allocated),
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return &models.Budget{
		ID: id, Code: code, Period: period, Allocated: allocated,
		Committed: committed, Spent: spent, Remaining: remaining, Dept: dept,
	}, nil
}

// CreateRfq inserts an RFQ row and audit trail entry.
func (p *Procurement) CreateRfq(ctx context.Context, title string, dueDate *time.Time, invited []string, requisitionID, auditUser string) (*models.Rfq, error) {
	title = strings.TrimSpace(title)
	if title == "" {
		return nil, fmt.Errorf("%w: title is required", ErrInvalidArgument)
	}
	if invited == nil {
		invited = []string{}
	}
	id := newProcurementID("RFQ")
	status := "Open"
	now := time.Now().UTC()
	createdDay := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, time.UTC)

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `
		INSERT INTO rfqs (id, title, status, due_date, created_at, winner_vendor_id, invited_vendor_ids, requisition_id)
		VALUES ($1,$2,$3,$4,$5,NULL,COALESCE($6::text[], '{}'),NULLIF($7,''))`,
		id, title, status, dueDate, createdDay, invited, strings.TrimSpace(requisitionID),
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("invited=%d", len(invited)),
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	out := models.Rfq{
		ID:             id,
		Title:          title,
		Status:         status,
		CreatedAt:      createdDay.Format("2006-01-02"),
		InvitedVendors: invited,
	}
	if dueDate != nil {
		out.DueDate = dueDate.UTC().Format("2006-01-02")
	}
	return &out, nil
}

// CreateGrn inserts a goods receipt note, its received lines, and an audit
// trail entry. Lines drive proportional budget spend recognition when the GRN
// is posted; a GRN with no lines recognizes the full PO remainder.
func (p *Procurement) CreateGrn(ctx context.Context, vendorID string, poID *string, receivedBy, status string, receivedDate *time.Time, lines []models.GrnLine, auditUser string) (*models.Grn, error) {
	vendorID = strings.TrimSpace(vendorID)
	if vendorID == "" {
		return nil, fmt.Errorf("%w: vendorId is required", ErrInvalidArgument)
	}
	if status == "" {
		status = "Draft"
	}
	if strings.TrimSpace(receivedBy) == "" {
		receivedBy = auditUser
	}
	rd := receivedDate
	if rd == nil {
		t := time.Now().UTC()
		d := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
		rd = &d
	}
	id := newProcurementID("GRN")

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if poID != nil {
		if err := p.assertPOReceivable(ctx, tx, *poID); err != nil {
			return nil, err
		}
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO grns (id, po_id, vendor_id, received_date, received_by, status)
		VALUES ($1,$2,$3,$4,$5,$6)`,
		id, poID, vendorID, rd, receivedBy, status,
	); err != nil {
		return nil, err
	}
	for _, ln := range lines {
		if strings.TrimSpace(ln.ItemID) == "" || ln.Qty <= 0 || ln.UnitPrice < 0 {
			return nil, fmt.Errorf("%w: invalid grn line qty/price/itemId", ErrInvalidArgument)
		}
		if _, err := tx.Exec(ctx, `INSERT INTO grn_lines (grn_id, item_id, qty, unit_price) VALUES ($1,$2,$3,$4)`,
			id, strings.TrimSpace(ln.ItemID), ln.Qty, ln.UnitPrice,
		); err != nil {
			return nil, err
		}
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	detail := fmt.Sprintf("vendor=%s", vendorID)
	if poID != nil && *poID != "" {
		detail += fmt.Sprintf(" po=%s", *poID)
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, detail,
	); err != nil {
		return nil, err
	}
	out := &models.Grn{
		ID: id, PoID: poID, VendorID: vendorID, ReceivedDate: rd.UTC().Format("2006-01-02"),
		ReceivedBy: receivedBy, Status: status, Lines: lines,
	}
	if err := p.recognizePOSpendOnReceipt(ctx, tx, out); err != nil {
		return nil, err
	}
	if err := p.enqueueGrnPosted(ctx, tx, out); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return out, nil
}

// CreateInvoice inserts an AP invoice row and audit trail entry.
func (p *Procurement) CreateInvoice(ctx context.Context, vendorID string, poID *string, amount float64, currency string, invoiceDate *time.Time, invoiceNo *string, auditUser string) (*models.Invoice, error) {
	vendorID = strings.TrimSpace(vendorID)
	if vendorID == "" {
		return nil, fmt.Errorf("%w: vendorId is required", ErrInvalidArgument)
	}
	if currency == "" {
		currency = "USD"
	}
	status := "Pending Approval"
	idate := invoiceDate
	if idate == nil {
		t := time.Now().UTC()
		d := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.UTC)
		idate = &d
	}
	id := newProcurementID("INV")

	var invNo interface{}
	if invoiceNo != nil && strings.TrimSpace(*invoiceNo) != "" {
		s := strings.TrimSpace(*invoiceNo)
		invNo = s
	}

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	// Three-way match: derive match_status from the linked PO and goods receipt.
	// No PO → "No PO"; PO with no posted GRN → "Pending GRN"; received and the
	// amount agrees with the PO total → "Matched"; received but amounts differ
	// → "Amount variance". Buyers clear variances downstream before payment.
	matchStatus, grnID, err := p.deriveInvoiceMatchStatus(ctx, tx, poID, amount)
	if err != nil {
		return nil, err
	}

	if _, err := tx.Exec(ctx, `
		INSERT INTO invoices (id, invoice_no, vendor_id, po_id, grn_id, amount, currency, status, match_status, invoice_date)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,
		id, invNo, vendorID, poID, grnID, amount, currency, status, matchStatus, idate,
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("vendor=%s amount=%.2f %s match=%s", vendorID, amount, currency, matchStatus),
	); err != nil {
		return nil, err
	}
	out := models.Invoice{
		ID: id, VendorID: vendorID, PoID: poID, GrnID: grnID, Amount: amount, Currency: currency,
		Status: status, MatchStatus: matchStatus, InvoiceDate: idate.UTC().Format("2006-01-02"),
	}
	if invoiceNo != nil && strings.TrimSpace(*invoiceNo) != "" {
		s := strings.TrimSpace(*invoiceNo)
		out.InvoiceNo = &s
	}
	if err := p.enqueueInvoiceReceived(ctx, tx, &out); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	return &out, nil
}

// deriveInvoiceMatchStatus runs the PO/GRN side of the three-way match for a new
// invoice, inside the caller's transaction. Returns one of "No PO",
// "Pending GRN", "Matched", or "Amount variance", plus the id of the posted GRN
// it matched against (nil when there is no PO or no posted receipt yet).
func (p *Procurement) deriveInvoiceMatchStatus(ctx context.Context, tx pgx.Tx, poID *string, amount float64) (string, *string, error) {
	pid := ""
	if poID != nil {
		pid = strings.TrimSpace(*poID)
	}
	if pid == "" {
		return "No PO", nil, nil
	}
	var poTotal float64
	err := tx.QueryRow(ctx, `SELECT total FROM purchase_orders WHERE id = $1`, pid).Scan(&poTotal)
	if err == pgx.ErrNoRows {
		return "No PO", nil, nil
	}
	if err != nil {
		return "", nil, err
	}
	var grnID *string
	if err := tx.QueryRow(ctx, `
		SELECT id FROM grns WHERE po_id = $1 AND lower(status) IN ('posted','received')
		ORDER BY received_date DESC NULLS LAST, id DESC LIMIT 1`,
		pid,
	).Scan(&grnID); err != nil && err != pgx.ErrNoRows {
		return "", nil, err
	}
	switch {
	case grnID == nil:
		return "Pending GRN", nil, nil
	case math.Abs(amount-poTotal) <= 0.01:
		return "Matched", grnID, nil
	default:
		return "Amount variance", grnID, nil
	}
}

// ApproveInvoice clears an invoice for payment, but only once its three-way
// match has resolved to "Matched" (PO + posted GRN + amount agreement). A
// pending or variance match returns ErrConflict so the buyer resolves it first;
// this is the gate that stops an unmatched invoice reaching finance. The status
// is recomputed from live data inside the tx to avoid trusting a stale value.
func (p *Procurement) ApproveInvoice(ctx context.Context, id, auditUser string) (*models.Invoice, error) {
	id = strings.TrimSpace(id)
	if id == "" {
		return nil, fmt.Errorf("%w: id is required", ErrInvalidArgument)
	}
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	var poID *string
	var amount float64
	var status string
	err = tx.QueryRow(ctx, `SELECT po_id, amount, status FROM invoices WHERE id = $1 FOR UPDATE`, id).
		Scan(&poID, &amount, &status)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	if strings.EqualFold(strings.TrimSpace(status), "Paid") {
		return nil, fmt.Errorf("%w: invoice %s is already paid", ErrConflict, id)
	}

	match, grnID, err := p.deriveInvoiceMatchStatus(ctx, tx, poID, amount)
	if err != nil {
		return nil, err
	}
	if match != "Matched" {
		return nil, fmt.Errorf("%w: invoice cannot be approved while three-way match is %q", ErrConflict, match)
	}

	if _, err := tx.Exec(ctx,
		`UPDATE invoices SET status = 'Approved', match_status = $2, grn_id = COALESCE(grn_id, $3) WHERE id = $1`,
		id, match, grnID,
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "approve", id, "invoice approved (three-way match cleared)",
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}

	out, err := p.GetInvoice(ctx, id)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CreateContract inserts a vendor contract row and audit trail entry.
func (p *Procurement) CreateContract(ctx context.Context, vendorID, title string, startDate, endDate *time.Time, value float64, currency, status string, auditUser string) (*models.Contract, error) {
	vendorID = strings.TrimSpace(vendorID)
	title = strings.TrimSpace(title)
	if vendorID == "" || title == "" {
		return nil, fmt.Errorf("%w: vendorId and title are required", ErrInvalidArgument)
	}
	if currency == "" {
		currency = "USD"
	}
	if status == "" {
		status = "Draft"
	}
	id := newProcurementID("CNT")

	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback(ctx)

	if _, err := tx.Exec(ctx, `
		INSERT INTO contracts (id, vendor_id, title, start_date, end_date, value, currency, status)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
		id, vendorID, title, startDate, endDate, value, currency, status,
	); err != nil {
		return nil, err
	}
	if auditUser == "" {
		auditUser = "unknown"
	}
	if _, err := tx.Exec(ctx, `
		INSERT INTO audit_entries (username, action, target, detail)
		VALUES ($1,$2,$3,$4)`,
		auditUser, "create", id, fmt.Sprintf("vendor=%s value=%.2f %s", vendorID, value, currency),
	); err != nil {
		return nil, err
	}
	if err := tx.Commit(ctx); err != nil {
		return nil, err
	}
	out := models.Contract{
		ID: id, VendorID: vendorID, Title: title, Value: value, Currency: currency, Status: status,
	}
	if startDate != nil {
		out.StartDate = startDate.UTC().Format("2006-01-02")
	}
	if endDate != nil {
		out.EndDate = endDate.UTC().Format("2006-01-02")
	}
	return &out, nil
}
