-- 027: Convert procurement surrogate entity ids from text to uuid
--
-- Every id in this service is already generated by uuid.NewString(); the columns
-- were simply declared TEXT. Retyping them makes the key type match the value
-- that has always been stored, and matches finance, warehouse, ERP and
-- production, which key on uuid.
--
-- WHAT IS DELIBERATELY NOT CONVERTED
--
--   procurement_event_outbox.id   bigint, and the relay reads the backlog in id
--                                 order. uuid has no ordering, so converting it
--                                 would break event delivery sequence.
--   kafka_dedupe.event_id         upstream event ids produced by other services.
--   processed_events.event_id     Rewriting them would break deduplication
--                                 against the ids those services actually send.
--   auth_users / auth_groups /    Django-heritage tables keyed by bigint and
--   auth_permissions              referenced by issued tokens.
--   api_audit_logs.id,            Log tables. Sequential keys are what makes
--   audit_entries.id,             them cheap to append and scan by time.
--   notifications.id
--   requisition_approval_desks    Composite natural key (chain_key, desk) —
--   requisition_approval_tiers    configuration, not entity identity.
--   requisitions.pm_requisition_id  Cross-service references. These hold ids
--   vendors.scm_business_id         owned by project-management and SCM, whose
--   api_audit_logs.resource_id      key types are theirs to decide, not ours.
--   procurement_external_refs.*     Correlation columns, intentionally text.
--
-- THREE SOFT REFERENCES
--
-- grns.po_id, invoices.grn_id and invoices.po_id hold ids but carry no foreign
-- key. They are converted with the same mapping as the columns they point at, or
-- they would silently dangle.
--
-- THE MAPPING
--
-- Values that are already uuid strings keep their exact value, so nothing that
-- has stored a procurement id elsewhere breaks. The only non-uuid ids in the
-- database are the three fuel SKUs seeded by 017 (ITEM-FUEL-DIESEL and friends);
-- they map deterministically, so parents and children land on the same value.
-- Those literals appear only in migrations — runtime code resolves fuel items by
-- items.sku ('FUEL-DIESEL'), which is untouched.

-- A table rewrite takes ACCESS EXCLUSIVE. Without a timeout, an ALTER that
-- cannot get the lock immediately waits in the lock queue — and every read that
-- arrives behind it queues too, so a migration run against live traffic stalls
-- the service rather than just itself. Failing after ten seconds leaves the
-- transaction rolled back and the table untouched; re-run it in a quiet window.
SET LOCAL lock_timeout = '10s';

CREATE OR REPLACE FUNCTION procurement_id_to_uuid(v TEXT) RETURNS UUID AS $$
    SELECT CASE
        WHEN v IS NULL OR v = '' THEN NULL
        WHEN v ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
            THEN v::uuid
        -- RFC 4122 v3 shape (md5-based) so the result is a well-formed uuid
        -- rather than 32 arbitrary hex digits.
        ELSE uuid_in(overlay(overlay(md5('iag:procurement:' || v)
                 placing '3' from 13) placing '8' from 17)::cstring)
    END
$$ LANGUAGE sql IMMUTABLE;

-- ALTER ... USING cannot contain a subquery, so the array mapping is wrapped in
-- its own function. WITH ORDINALITY keeps the invitation order the column had.
CREATE OR REPLACE FUNCTION procurement_ids_to_uuid(v TEXT[]) RETURNS UUID[] AS $$
    SELECT COALESCE(array_agg(procurement_id_to_uuid(x) ORDER BY ord), '{}'::uuid[])
      FROM unnest(v) WITH ORDINALITY AS t(x, ord)
$$ LANGUAGE sql IMMUTABLE;

-- ---- trigram search indexes on id columns ---------------------------------
-- 024 indexed purchase_orders.id/vendor_id and invoices.id/vendor_id with
-- gin_trgm_ops so the UI can search on a fragment of an id. gin_trgm_ops does
-- not accept uuid, so these are dropped before the retype and recreated below
-- over id::text — the cast is immutable, so partial-id search keeps working
-- exactly as it does today.
DROP INDEX IF EXISTS purchase_orders_id_trgm_idx;
DROP INDEX IF EXISTS purchase_orders_vendor_id_trgm_idx;
DROP INDEX IF EXISTS invoices_id_trgm_idx;
DROP INDEX IF EXISTS invoices_vendor_id_trgm_idx;

-- ---- drop the foreign keys ------------------------------------------------
ALTER TABLE contracts                 DROP CONSTRAINT contracts_vendor_id_fkey;
ALTER TABLE grn_lines                 DROP CONSTRAINT grn_lines_grn_id_fkey;
ALTER TABLE grn_lines                 DROP CONSTRAINT grn_lines_item_id_fkey;
ALTER TABLE grns                      DROP CONSTRAINT grns_vendor_id_fkey;
ALTER TABLE invoices                  DROP CONSTRAINT invoices_vendor_id_fkey;
ALTER TABLE items                     DROP CONSTRAINT items_preferred_vendor_id_fkey;
ALTER TABLE payments                  DROP CONSTRAINT payments_invoice_id_fkey;
ALTER TABLE payments                  DROP CONSTRAINT payments_vendor_id_fkey;
ALTER TABLE po_lines                  DROP CONSTRAINT po_lines_item_id_fkey;
ALTER TABLE po_lines                  DROP CONSTRAINT po_lines_po_id_fkey;
ALTER TABLE purchase_orders           DROP CONSTRAINT purchase_orders_budget_id_fkey;
ALTER TABLE purchase_orders           DROP CONSTRAINT purchase_orders_requisition_id_fkey;
ALTER TABLE purchase_orders           DROP CONSTRAINT purchase_orders_vendor_id_fkey;
ALTER TABLE requisition_approval_state DROP CONSTRAINT requisition_approval_state_requisition_id_fkey;
ALTER TABLE requisition_approval_steps DROP CONSTRAINT requisition_approval_steps_requisition_id_fkey;
ALTER TABLE requisition_approvals     DROP CONSTRAINT requisition_approvals_requisition_id_fkey;
ALTER TABLE requisitions              DROP CONSTRAINT requisitions_budget_id_fkey;
ALTER TABLE rfq_quotes                DROP CONSTRAINT rfq_quotes_rfq_id_fkey;
ALTER TABLE rfq_quotes                DROP CONSTRAINT rfq_quotes_vendor_id_fkey;
ALTER TABLE rfqs                      DROP CONSTRAINT rfqs_requisition_id_fkey;
ALTER TABLE rfqs                      DROP CONSTRAINT rfqs_winner_vendor_id_fkey;

-- ---- primary keys ---------------------------------------------------------
ALTER TABLE budgets              ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE contracts            ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE grns                 ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE invoices             ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE items                ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE payments             ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE purchase_orders      ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE requisition_approvals ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE requisitions         ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE rfq_quotes           ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE rfqs                 ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);
ALTER TABLE vendors              ALTER COLUMN id TYPE UUID USING procurement_id_to_uuid(id);

-- ---- referencing columns --------------------------------------------------
ALTER TABLE purchase_orders            ALTER COLUMN budget_id      TYPE UUID USING procurement_id_to_uuid(budget_id);
ALTER TABLE requisitions               ALTER COLUMN budget_id      TYPE UUID USING procurement_id_to_uuid(budget_id);
ALTER TABLE grn_lines                  ALTER COLUMN grn_id         TYPE UUID USING procurement_id_to_uuid(grn_id);
ALTER TABLE invoices                   ALTER COLUMN grn_id         TYPE UUID USING procurement_id_to_uuid(grn_id);
ALTER TABLE payments                   ALTER COLUMN invoice_id     TYPE UUID USING procurement_id_to_uuid(invoice_id);
ALTER TABLE grn_lines                  ALTER COLUMN item_id        TYPE UUID USING procurement_id_to_uuid(item_id);
ALTER TABLE po_lines                   ALTER COLUMN item_id        TYPE UUID USING procurement_id_to_uuid(item_id);
ALTER TABLE po_lines                   ALTER COLUMN po_id          TYPE UUID USING procurement_id_to_uuid(po_id);
ALTER TABLE grns                       ALTER COLUMN po_id          TYPE UUID USING procurement_id_to_uuid(po_id);
ALTER TABLE invoices                   ALTER COLUMN po_id          TYPE UUID USING procurement_id_to_uuid(po_id);
ALTER TABLE purchase_orders            ALTER COLUMN requisition_id TYPE UUID USING procurement_id_to_uuid(requisition_id);
ALTER TABLE requisition_approval_state ALTER COLUMN requisition_id TYPE UUID USING procurement_id_to_uuid(requisition_id);
ALTER TABLE requisition_approval_steps ALTER COLUMN requisition_id TYPE UUID USING procurement_id_to_uuid(requisition_id);
ALTER TABLE requisition_approvals      ALTER COLUMN requisition_id TYPE UUID USING procurement_id_to_uuid(requisition_id);
ALTER TABLE rfqs                       ALTER COLUMN requisition_id TYPE UUID USING procurement_id_to_uuid(requisition_id);
ALTER TABLE rfq_quotes                 ALTER COLUMN rfq_id         TYPE UUID USING procurement_id_to_uuid(rfq_id);
ALTER TABLE contracts                  ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE grns                       ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE invoices                   ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE items                      ALTER COLUMN preferred_vendor_id TYPE UUID USING procurement_id_to_uuid(preferred_vendor_id);
ALTER TABLE payments                   ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE purchase_orders            ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE rfq_quotes                 ALTER COLUMN vendor_id      TYPE UUID USING procurement_id_to_uuid(vendor_id);
ALTER TABLE rfqs                       ALTER COLUMN winner_vendor_id TYPE UUID USING procurement_id_to_uuid(winner_vendor_id);

-- The invited-vendor array carries vendor ids with no foreign key to enforce
-- them, so it is mapped with the same function as the columns it points at.
ALTER TABLE rfqs ALTER COLUMN invited_vendor_ids DROP DEFAULT;
ALTER TABLE rfqs ALTER COLUMN invited_vendor_ids TYPE UUID[]
    USING procurement_ids_to_uuid(invited_vendor_ids);
ALTER TABLE rfqs ALTER COLUMN invited_vendor_ids SET DEFAULT '{}';

-- ---- restore the foreign keys ---------------------------------------------
ALTER TABLE contracts       ADD CONSTRAINT contracts_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE grn_lines       ADD CONSTRAINT grn_lines_grn_id_fkey FOREIGN KEY (grn_id) REFERENCES grns(id) ON DELETE CASCADE;
ALTER TABLE grn_lines       ADD CONSTRAINT grn_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
ALTER TABLE grns            ADD CONSTRAINT grns_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE invoices        ADD CONSTRAINT invoices_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE items           ADD CONSTRAINT items_preferred_vendor_id_fkey FOREIGN KEY (preferred_vendor_id) REFERENCES vendors(id);
ALTER TABLE payments        ADD CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id);
ALTER TABLE payments        ADD CONSTRAINT payments_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE po_lines        ADD CONSTRAINT po_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES items(id);
ALTER TABLE po_lines        ADD CONSTRAINT po_lines_po_id_fkey FOREIGN KEY (po_id) REFERENCES purchase_orders(id) ON DELETE CASCADE;
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES budgets(id);
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES requisitions(id);
ALTER TABLE purchase_orders ADD CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE requisition_approval_state ADD CONSTRAINT requisition_approval_state_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES requisitions(id) ON DELETE CASCADE;
ALTER TABLE requisition_approval_steps ADD CONSTRAINT requisition_approval_steps_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES requisitions(id) ON DELETE CASCADE;
ALTER TABLE requisition_approvals ADD CONSTRAINT requisition_approvals_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES requisitions(id) ON DELETE CASCADE;
ALTER TABLE requisitions    ADD CONSTRAINT requisitions_budget_id_fkey FOREIGN KEY (budget_id) REFERENCES budgets(id);
ALTER TABLE rfq_quotes      ADD CONSTRAINT rfq_quotes_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES rfqs(id) ON DELETE CASCADE;
ALTER TABLE rfq_quotes      ADD CONSTRAINT rfq_quotes_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES vendors(id);
ALTER TABLE rfqs            ADD CONSTRAINT rfqs_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES requisitions(id);
ALTER TABLE rfqs            ADD CONSTRAINT rfqs_winner_vendor_id_fkey FOREIGN KEY (winner_vendor_id) REFERENCES vendors(id);

-- ---- restore trigram search over the text rendering of the id -------------
CREATE INDEX IF NOT EXISTS purchase_orders_id_trgm_idx
    ON purchase_orders USING gin ((id::text) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS purchase_orders_vendor_id_trgm_idx
    ON purchase_orders USING gin ((vendor_id::text) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS invoices_id_trgm_idx
    ON invoices USING gin ((id::text) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS invoices_vendor_id_trgm_idx
    ON invoices USING gin ((vendor_id::text) gin_trgm_ops);

-- ---- generate ids in the database from here on ----------------------------
-- The Go layer still supplies uuid.NewString() on insert; these defaults mean a
-- direct SQL insert no longer has to.
ALTER TABLE budgets               ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE contracts             ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE grns                  ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE invoices              ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE items                 ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE payments              ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE purchase_orders       ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE requisition_approvals ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE requisitions          ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE rfq_quotes            ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE rfqs                  ALTER COLUMN id SET DEFAULT gen_random_uuid();
ALTER TABLE vendors               ALTER COLUMN id SET DEFAULT gen_random_uuid();

DROP FUNCTION procurement_ids_to_uuid(TEXT[]);
DROP FUNCTION procurement_id_to_uuid(TEXT);
