-- 031: give the documents back their human-facing number
--
-- Migration 027 retyped every entity id from TEXT to UUID on the premise that
-- "every id in this service is already generated by uuid.NewString()". That was
-- not true: newProcurementID() produces PREFIX-<8 hex> — PR-2026-1a2b3c4d,
-- PO-2026-…, RFQ-…, GRN-…, INV-…, CNT-…, BDG-…, V-…, QT-…, PMT-… — and every
-- Create* in the repo inserted one explicitly.
--
-- The result is that on any database that has run 027, every create fails with
--
--     invalid input syntax for type uuid: "BDG-068cc655" (SQLSTATE 22P02)
--
-- and the whole write surface of the service is dead. Only CreateItem was
-- fixed, by omitting the id and letting the column default fill it; its comment
-- records that the rest were left because the prefixes "look like human-facing
-- references … deciding where that number lives now is a design question".
--
-- This is that decision. The number lives in its own column.
--
-- Three tables already had one and are untouched: invoices.invoice_no,
-- budgets.code and payments.reference. Five did not, because their number was
-- the primary key. They get doc_no, which is what a person quotes in an email
-- or writes on a delivery note, while id goes back to being a surrogate key
-- nobody has to read.
--
-- Vendors and RFQ quotes get nothing: "V-1a2b3c4d" and "QT-…" were never
-- references anyone used — a vendor is known by its name and a quote by its
-- supplier and amount.
--
-- Existing rows keep a NULL doc_no. 027 hashed the old text ids through
-- md5('iag:procurement:' || id) with no mapping preserved, so the numbers those
-- rows used to carry cannot be recovered. Inventing new ones would be worse
-- than leaving the column empty: a document that has been quoted on paper under
-- one number must not silently acquire another.

ALTER TABLE requisitions     ADD COLUMN IF NOT EXISTS doc_no TEXT;
ALTER TABLE purchase_orders  ADD COLUMN IF NOT EXISTS doc_no TEXT;
ALTER TABLE rfqs             ADD COLUMN IF NOT EXISTS doc_no TEXT;
ALTER TABLE grns             ADD COLUMN IF NOT EXISTS doc_no TEXT;
ALTER TABLE contracts        ADD COLUMN IF NOT EXISTS doc_no TEXT;

-- Unique where present. A partial index so the NULLs on legacy rows do not
-- collide with each other.
CREATE UNIQUE INDEX IF NOT EXISTS requisitions_doc_no_key
    ON requisitions (doc_no) WHERE doc_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS purchase_orders_doc_no_key
    ON purchase_orders (doc_no) WHERE doc_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS rfqs_doc_no_key
    ON rfqs (doc_no) WHERE doc_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS grns_doc_no_key
    ON grns (doc_no) WHERE doc_no IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS contracts_doc_no_key
    ON contracts (doc_no) WHERE doc_no IS NOT NULL;
