package rbac

// Permission codes (Django-style dotted codenames).
const (
	ViewUser         = "auth.view_user"
	ChangeUser       = "auth.change_user"
	ViewGroup        = "auth.view_group"
	ChangeGroup      = "auth.change_group"
	ViewPermission   = "auth.view_permission"
	ViewSeed         = "procurement.view_seed"
	AddRequisition   = "procurement.add_requisition"
	ChangeRequisition = "procurement.change_requisition"
	DeleteRequisition = "procurement.delete_requisition"
	AddPurchaseOrder = "procurement.add_purchase_order"
	ChangePurchaseOrder = "procurement.change_purchase_order"
	DeletePurchaseOrder = "procurement.delete_purchase_order"
	AddVendor        = "procurement.add_vendor"
	ChangeVendor     = "procurement.change_vendor"
	DeleteVendor     = "procurement.delete_vendor"
	AddItem          = "procurement.add_item"
	ChangeItem       = "procurement.change_item"
	DeleteItem       = "procurement.delete_item"
	AddBudget        = "procurement.add_budget"
	ChangeBudget     = "procurement.change_budget"
	DeleteBudget     = "procurement.delete_budget"
	ManageBudgetPeriod = "procurement.manage_budget_period"
	AddRfq           = "procurement.add_rfq"
	ChangeRfq        = "procurement.change_rfq"
	DeleteRfq        = "procurement.delete_rfq"
	AddGrn           = "procurement.add_grn"
	ChangeGrn        = "procurement.change_grn"
	DeleteGrn        = "procurement.delete_grn"
	AddInvoice       = "procurement.add_invoice"
	ChangeInvoice    = "procurement.change_invoice"
	DeleteInvoice    = "procurement.delete_invoice"
	AddContract      = "procurement.add_contract"
	ChangeContract   = "procurement.change_contract"
	DeleteContract   = "procurement.delete_contract"
	ViewAPIAudit     = "audit.view_api_log"
	ViewInbox        = "procurement.view_inbox"
	EmitNotification = "procurement.emit_notification"
	ViewOwnPO        = "procurement.view_own_po"
	ViewOwnInvoice   = "procurement.view_own_invoice"
)
